
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateReleaseParameters {
    /**
    * Label: Repository Name, type: entry
    */
    String repoName
    /**
    * Label: , type: radio
    */
    String updateAction
    /**
    * Label: Release Name, type: entry
    */
    String releaseName
    /**
    * Label: Tag Name, type: entry
    */
    String tagName
    /**
    * Label: Source Commit, type: entry
    */
    String commitish
    /**
    * Label: Release Body, type: textarea
    */
    String body
    /**
    * Label: Release Assets, type: entry
    */
    String assets
    /**
    * Label: Prerelease?, type: checkbox
    */
    boolean prerelease
    /**
    * Label: Delete Old Tag?, type: checkbox
    */
    boolean deleteOldTag

    static CreateReleaseParameters initParameters(StepParameters sp) {
        CreateReleaseParameters parameters = new CreateReleaseParameters()

        def repoName = sp.getRequiredParameter('repoName').value
        parameters.repoName = repoName
        def updateAction = sp.getRequiredParameter('updateAction').value
        parameters.updateAction = updateAction
        def releaseName = sp.getParameter('releaseName').value
        parameters.releaseName = releaseName
        def tagName = sp.getRequiredParameter('tagName').value
        parameters.tagName = tagName
        def commitish = sp.getParameter('commitish').value
        parameters.commitish = commitish
        def body = sp.getParameter('body').value
        parameters.body = body
        def assets = sp.getParameter('assets').value
        parameters.assets = assets
        def prerelease = sp.getParameter('prerelease').value == "true"
        parameters.prerelease = prerelease
        def deleteOldTag = sp.getParameter('deleteOldTag').value == "true"
        parameters.deleteOldTag = deleteOldTag

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 323a0d7630e264e8d9eed938af9d03be ===
