
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreatePullRequestParameters {
    /**
    * Label: Repository Name, type: entry
    */
    String repository
    /**
    * Label: Base, type: entry
    */
    String base
    /**
    * Label: Head, type: entry
    */
    String head
    /**
    * Label: Title, type: textarea
    */
    String title
    /**
    * Label: Body, type: textarea
    */
    String body
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultProperty

    static CreatePullRequestParameters initParameters(StepParameters sp) {
        CreatePullRequestParameters parameters = new CreatePullRequestParameters()

        def repository = sp.getRequiredParameter('repository').value
        parameters.repository = repository
        def base = sp.getRequiredParameter('base').value
        parameters.base = base
        def head = sp.getRequiredParameter('head').value
        parameters.head = head
        def title = sp.getParameter('title').value
        parameters.title = title
        def body = sp.getParameter('body').value
        parameters.body = body
        def resultProperty = sp.getRequiredParameter('resultProperty').value
        parameters.resultProperty = resultProperty

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: ba5077619f0cd84dcdd46cde1c1ed155 ===
