
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateRepositoryParameters {
    /**
    * Label: Owner, type: entry
    */
    String owner
    /**
    * Label: Repository Name, type: entry
    */
    String repo
    /**
    * Label: Repository Description, type: textarea
    */
    String description
    /**
    * Label: Public?, type: checkbox
    */
    boolean publicParam
    /**
    * Label: Teams, type: textarea
    */
    String teams
    /**
    * Label: Branch Protection Rules, type: textarea
    */
    String branchProtectionRules
    /**
    * Label: Add License?, type: checkbox
    */
    boolean addLicense
    /**
    * Label: License File, type: entry
    */
    String licenseFile

    static CreateRepositoryParameters initParameters(StepParameters sp) {
        CreateRepositoryParameters parameters = new CreateRepositoryParameters()

        def owner = sp.getRequiredParameter('owner').value
        parameters.owner = owner
        def repo = sp.getRequiredParameter('repo').value
        parameters.repo = repo
        def description = sp.getParameter('description').value
        parameters.description = description
        def publicParam = sp.getParameter('public').value == "true"
        parameters.publicParam = publicParam
        def teams = sp.getParameter('teams').value
        parameters.teams = teams
        def branchProtectionRules = sp.getParameter('branchProtectionRules').value
        parameters.branchProtectionRules = branchProtectionRules
        def addLicense = sp.getParameter('addLicense').value == "true"
        parameters.addLicense = addLicense
        def licenseFile = sp.getParameter('licenseFile').value
        parameters.licenseFile = licenseFile

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 0d1d90dd635c39b4428e3db8755628b0 ===
