
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class DownloadReleaseAssetParameters {
    /**
    * Label: Repository Name, type: entry
    */
    String repoName
    /**
    * Label: Tag Name, type: entry
    */
    String tagName
    /**
    * Label: Asset Name, type: entry
    */
    String assetName
    /**
    * Label: Asset Path, type: entry
    */
    String assetPath

    static DownloadReleaseAssetParameters initParameters(StepParameters sp) {
        DownloadReleaseAssetParameters parameters = new DownloadReleaseAssetParameters()

        def repoName = sp.getRequiredParameter('repoName').value
        parameters.repoName = repoName
        def tagName = sp.getRequiredParameter('tagName').value
        parameters.tagName = tagName
        def assetName = sp.getRequiredParameter('assetName').value
        parameters.assetName = assetName
        def assetPath = sp.getParameter('assetPath').value
        parameters.assetPath = assetPath

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: abb65951bf90b4957f476e646f508385 ===
