
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class FindPullRequestsParameters {
    /**
    * Label: Repository Name, type: entry
    */
    String repoName
    /**
    * Label: Branch Name, type: entry
    */
    String branchName

    static FindPullRequestsParameters initParameters(StepParameters sp) {
        FindPullRequestsParameters parameters = new FindPullRequestsParameters()

        def repoName = sp.getRequiredParameter('repoName').value
        parameters.repoName = repoName
        def branchName = sp.getParameter('branchName').value
        parameters.branchName = branchName

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 5b9a5f4e8b40f38e6ba0319c36053c3c ===
