
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetCommitParameters {
    /**
    * Label: Repository Name, type: entry
    */
    String repoName
    /**
    * Label: Commit SHA, type: entry
    */
    String sha
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static GetCommitParameters initParameters(StepParameters sp) {
        GetCommitParameters parameters = new GetCommitParameters()

        def repoName = sp.getRequiredParameter('repoName').value
        parameters.repoName = repoName
        def sha = sp.getRequiredParameter('sha').value
        parameters.sha = sha
        def resultPropertySheet = sp.getParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 71d66b3642c5e9d10604a71aeb65527a ===
