
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class SetupWebhookParameters {
    /**
    * Label: , type: textarea
    */
    String repositoryNames
    /**
    * Label: , type: entry
    */
    String ec_trigger
    /**
    * Label: , type: credential
    */
    String credential

    static SetupWebhookParameters initParameters(StepParameters sp) {
        SetupWebhookParameters parameters = new SetupWebhookParameters()

        def repositoryNames = sp.getParameter('repositoryNames').value
        parameters.repositoryNames = repositoryNames
        def ec_trigger = sp.getParameter('ec_trigger').value
        parameters.ec_trigger = ec_trigger
        def credential = sp.getParameter('credential').value
        parameters.credential = credential

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 8229d720c48b74cfe1eb06214d9dc528 ===
