
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class UploadFilesParameters {
    /**
    * Label: Repository Owner, type: entry
    */
    String ownerName
    /**
    * Label: Repository Name, type: entry
    */
    String repoName
    /**
    * Label: Source Directory, type: entry
    */
    String sourceDirectory
    /**
    * Label: Mapping, type: textarea
    */
    String mapping
    /**
    * Label: Files, type: textarea
    */
    String files
    /**
    * Label: Branch, type: entry
    */
    String branch
    /**
    * Label: Create Pull Request?, type: checkbox
    */
    boolean createPr

    static UploadFilesParameters initParameters(StepParameters sp) {
        UploadFilesParameters parameters = new UploadFilesParameters()

        def ownerName = sp.getRequiredParameter('ownerName').value
        parameters.ownerName = ownerName
        def repoName = sp.getRequiredParameter('repoName').value
        parameters.repoName = repoName
        def sourceDirectory = sp.getParameter('sourceDirectory').value
        parameters.sourceDirectory = sourceDirectory
        def mapping = sp.getParameter('mapping').value
        parameters.mapping = mapping
        def files = sp.getParameter('files').value
        parameters.files = files
        def branch = sp.getParameter('branch').value
        parameters.branch = branch
        def createPr = sp.getParameter('createPr').value == "true"
        parameters.createPr = createPr

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 4b43c239bd1ae99a0a5b106011020f05 ===
