
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class WebhookParameters {
    /**
    * Label: , type: textarea
    */
    String repositories
    /**
    * Label: , type: checkbox
    */
    boolean pushEvent
    /**
    * Label: , type: checkbox
    */
    boolean createPrEvent
    /**
    * Label: , type: textarea
    */
    String prAction
    /**
    * Label: , type: textarea
    */
    String includeBranches
    /**
    * Label: , type: textarea
    */
    String excludeBranches

    static WebhookParameters initParameters(StepParameters sp) {
        WebhookParameters parameters = new WebhookParameters()

        def repositories = sp.getParameter('repositories').value
        parameters.repositories = repositories
        def pushEvent = sp.getParameter('pushEvent').value == "true"
        parameters.pushEvent = pushEvent
        def createPrEvent = sp.getParameter('createPrEvent').value == "true"
        parameters.createPrEvent = createPrEvent
        def prAction = sp.getParameter('prAction').value
        parameters.prAction = prAction
        def includeBranches = sp.getParameter('includeBranches').value
        parameters.includeBranches = includeBranches
        def excludeBranches = sp.getParameter('excludeBranches').value
        parameters.excludeBranches = excludeBranches

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 7ea02aa434be589c7512ca3340e5a839 ===
