
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class WebhookParameters {
    /**
    * Label: , type: textarea
    */
    String repositories
    /**
    * Label: Process Push?, type: checkbox
    */
    boolean pushEvent
    /**
    * Label: Process Pull Request?, type: checkbox
    */
    boolean prEvent
    /**
    * Label: , type: textarea
    */
    String prAction
    /**
    * Label: , type: textarea
    */
    String includeBranches
    /**
    * Label: , type: textarea
    */
    String excludeBranches

    static WebhookParameters initParameters(StepParameters sp) {
        WebhookParameters parameters = new WebhookParameters()

        def repositories = sp.getParameter('repositories').value
        parameters.repositories = repositories
        def pushEvent = sp.getParameter('pushEvent').value == "true"
        parameters.pushEvent = pushEvent
        def prEvent = sp.getParameter('prEvent').value == "true"
        parameters.prEvent = prEvent
        def prAction = sp.getParameter('prAction').value
        parameters.prAction = prAction
        def includeBranches = sp.getParameter('includeBranches').value
        parameters.includeBranches = includeBranches
        def excludeBranches = sp.getParameter('excludeBranches').value
        parameters.excludeBranches = excludeBranches

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: a8af8af52c6d0c0db18ff4c6be5430e5 ===
